### ISSUE TITLE
Apache Tika & Storm = FileNotFoundException

### ISSUE THREAD

**Issue by tammomueller** [DigitalPebble/storm-crawler#1]
Hi,

I am unable to run in LocalCluster mode (actually haven't tried to deploy this).
I am always getting a FileNotFoundException. Can you actually run this code without any issues?

4518 [Thread-10] INFO  backtype.storm.daemon.supervisor - Copying resources at jar:file:/Users/tammomueller/.m2/repository/edu/ucar/netcdf/4.2-min/netcdf-4.2-min.jar!/resources to /var/folders/wj/bplcpvpd07s525n5vnfm0gyw0000gn/T//cc4ea00d-14a5-41b6-8178-7bb2a2f8da46/supervisor/stormdist/crawl-1-1371622362/resources
4524 [Thread-10] ERROR backtype.storm.event - Error when processing event
java.io.FileNotFoundException: Source 'file:/Users/tammomueller/.m2/repository/edu/ucar/netcdf/4.2-min/netcdf-4.2-min.jar!/resources' does not exist
    at org.apache.commons.io.FileUtils.copyDirectory(FileUtils.java:1368) ~[commons-io-2.4.jar:2.4]
    at org.apache.commons.io.FileUtils.copyDirectory(FileUtils.java:1261) ~[commons-io-2.4.jar:2.4]
    at org.apache.commons.io.FileUtils.copyDirectory(FileUtils.java:1230) ~[commons-io-2.4.jar:2.4]
    at backtype.storm.daemon.supervisor$fn__5073.invoke(supervisor.clj:452) ~[storm-core-0.9.0-wip17.jar:na]
    at clojure.lang.MultiFn.invoke(MultiFn.java:172) ~[clojure-1.4.0.jar:na]
    at backtype.storm.daemon.supervisor$mk_synchronize_supervisor$this__4986.invoke(supervisor.clj:290) ~[storm-core-0.9.0-wip17.jar:na]

Same issue reported on storm and Tika:
https://github.com/nathanmarz/storm/issues/82

**Comment by smirnp** [comment]
I have the same problem while debugging and submitting topologies locally on Windows 8.1. 
Doing 
new File("storm-starter-2.0.0-SNAPSHOT.jar!/resources").exists()
new File("storm-starter-2.0.0-SNAPSHOT.jar!\resources").exists()
gives false, while 
new File("storm-starter-2.0.0-SNAPSHOT.jar").exists() gives true.
On linux everything is ok.
