### ISSUE TITLE
Fails run CrawlTopology with java.lang.NoClassDefFoundError: org/w3c/dom/ElementTraversal

### ISSUE THREAD

**Issue by jiangyt** [DigitalPebble/storm-crawler#212]
Hi, 
I just clone the repository, followed the guide to run the topology in local cluster, but unluckily failed with following exceptions

7493 [Thread-22-sitemap] ERROR backtype.storm.util - Async loop died!
java.lang.NoClassDefFoundError: org/w3c/dom/ElementTraversal
        at java.lang.ClassLoader.defineClass1(Native Method) ~[na:1.7.0_80]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:800) ~[na:1.7.0_80]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[na:1.7.0_80]
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449) ~[na:1.7.0_80]
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71) ~[na:1.7.0_80]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361) ~[na:1.7.0_80]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355) ~[na:1.7.0_80]
        at java.security.AccessController.doPrivileged(Native Method) ~[na:1.7.0_80]
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354) ~[na:1.7.0_80]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[na:1.7.0_80]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[na:1.7.0_80]
        at org.apache.xerces.parsers.AbstractDOMParser.startDocument(Unknown Source) ~[xercesImpl-2.11.0.jar:na]
        at org.apache.xerces.impl.dtd.XMLDTDValidator.startDocument(Unknown Source) ~[xercesImpl-2.11.0.jar:na]
        at org.apache.xerces.impl.XMLDocumentScannerImpl.startEntity(Unknown Source) ~[xercesImpl-2.11.0.jar:na]
        at org.apache.xerces.impl.XMLVersionDetector.startDocumentParsing(Unknown Source) ~[xercesImpl-2.11.0.jar:na]
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source) ~[xercesImpl-2.11.0.jar:na]
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source) ~[xercesImpl-2.11.0.jar:na]
        at org.apache.xerces.parsers.XMLParser.parse(Unknown Source) ~[xercesImpl-2.11.0.jar:na]
        at org.apache.xerces.parsers.DOMParser.parse(Unknown Source) ~[xercesImpl-2.11.0.jar:na]
        at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source) ~[xercesImpl-2.11.0.jar:na]
        at com.digitalpebble.storm.crawler.filtering.regex.RegexURLNormalizer.readConfiguration(RegexURLNormalizer.java:168) ~[classes/:na]
        at com.digitalpebble.storm.crawler.filtering.regex.RegexURLNormalizer.readRules(RegexURLNormalizer.java:156) ~[classes/:na]
        at com.digitalpebble.storm.crawler.filtering.regex.RegexURLNormalizer.configure(RegexURLNormalizer.java:89) ~[classes/:na]
        at com.digitalpebble.storm.crawler.filtering.URLFilters.configure(URLFilters.java:136) ~[classes/:na]
        at com.digitalpebble.storm.crawler.filtering.URLFilters.<init>(URLFilters.java:68) ~[classes/:na]
        at com.digitalpebble.storm.crawler.bolt.SiteMapParserBolt.prepare(SiteMapParserBolt.java:298) ~[classes/:na]
        at backtype.storm.daemon.executor$fn__3439$fn__3451.invoke(executor.clj:692) ~[storm-core-0.9.5.jar:0.9.5]
        at backtype.storm.util$async_loop$fn__460.invoke(util.clj:461) ~[storm-core-0.9.5.jar:0.9.5]
        at clojure.lang.AFn.run(AFn.java:24) [clojure-1.5.1.jar:na]
        at java.lang.Thread.run(Thread.java:745) [na:1.7.0_80]
Caused by: java.lang.ClassNotFoundException: org.w3c.dom.ElementTraversal
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366) ~[na:1.7.0_80]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355) ~[na:1.7.0_80]
        at java.security.AccessController.doPrivileged(Native Method) ~[na:1.7.0_80]
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354) ~[na:1.7.0_80]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[na:1.7.0_80]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[na:1.7.0_80]
        ... 30 common frames omitted
7494 [Thread-22-sitemap] ERROR backtype.storm.daemon.executor - 
java.lang.NoClassDefFoundError: org/w3c/dom/ElementTraversal
        at java.lang.ClassLoader.defineClass1(Native Method) ~[na:1.7.0_80]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:800) ~[na:1.7.0_80]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[na:1.7.0_80]
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449) ~[na:1.7.0_80]
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71) ~[na:1.7.0_80]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361) ~[na:1.7.0_80]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355) ~[na:1.7.0_80]
        at java.security.AccessController.doPrivileged(Native Method) ~[na:1.7.0_80]
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354) ~[na:1.7.0_80]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[na:1.7.0_80]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[na:1.7.0_80]
        at org.apache.xerces.parsers.AbstractDOMParser.startDocument(Unknown Source) ~[xercesImpl-2.11.0.jar:na]
        at org.apache.xerces.impl.dtd.XMLDTDValidator.startDocument(Unknown Source) ~[xercesImpl-2.11.0.jar:na]
        at org.apache.xerces.impl.XMLDocumentScannerImpl.startEntity(Unknown Source) ~[xercesImpl-2.11.0.jar:na]
        at org.apache.xerces.impl.XMLVersionDetector.startDocumentParsing(Unknown Source) ~[xercesImpl-2.11.0.jar:na]
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source) ~[xercesImpl-2.11.0.jar:na]
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source) ~[xercesImpl-2.11.0.jar:na]
        at org.apache.xerces.parsers.XMLParser.parse(Unknown Source) ~[xercesImpl-2.11.0.jar:na]
        at org.apache.xerces.parsers.DOMParser.parse(Unknown Source) ~[xercesImpl-2.11.0.jar:na]
        at org.apache.xerces.jaxp.DocumentBuilderImpl.parse(Unknown Source) ~[xercesImpl-2.11.0.jar:na]
        at com.digitalpebble.storm.crawler.filtering.regex.RegexURLNormalizer.readConfiguration(RegexURLNormalizer.java:168) ~[classes/:na]
        at com.digitalpebble.storm.crawler.filtering.regex.RegexURLNormalizer.readRules(RegexURLNormalizer.java:156) ~[classes/:na]
        at com.digitalpebble.storm.crawler.filtering.regex.RegexURLNormalizer.configure(RegexURLNormalizer.java:89) ~[classes/:na]
        at com.digitalpebble.storm.crawler.filtering.URLFilters.configure(URLFilters.java:136) ~[classes/:na]
        at com.digitalpebble.storm.crawler.filtering.URLFilters.<init>(URLFilters.java:68) ~[classes/:na]
        at com.digitalpebble.storm.crawler.bolt.SiteMapParserBolt.prepare(SiteMapParserBolt.java:298) ~[classes/:na]
        at backtype.storm.daemon.executor$fn__3439$fn__3451.invoke(executor.clj:692) ~[storm-core-0.9.5.jar:0.9.5]
        at backtype.storm.util$async_loop$fn__460.invoke(util.clj:461) ~[storm-core-0.9.5.jar:0.9.5]
        at clojure.lang.AFn.run(AFn.java:24) [clojure-1.5.1.jar:na]
        at java.lang.Thread.run(Thread.java:745) [na:1.7.0_80]
Caused by: java.lang.ClassNotFoundException: org.w3c.dom.ElementTraversal
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366) ~[na:1.7.0_80]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355) ~[na:1.7.0_80]
        at java.security.AccessController.doPrivileged(Native Method) ~[na:1.7.0_80]
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354) ~[na:1.7.0_80]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[na:1.7.0_80]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[na:1.7.0_80]
        ... 30 common frames omitted

**Comment by jnioche** [comment]
Thanks @jiangyt.  This is strange, this class should be available as a dependency of Xerces.

Which command did you run to start the topology?

java -version? Did you install Storm on your machine?

**Comment by jiangyt** [comment]
Hi @jnioche  here's my environments

java -version
<pre><code>java version "1.7.0_80"
Java(TM) SE Runtime Environment (build 1.7.0_80-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.80-b11, mixed mode
</code></pre>

runs in local mode, havn't installed Storm
<pre><code>mvn clean compile exec:java -Dstorm.topology=com.digitalpebble.storm.crawler.CrawlTopology -Dexec.args="-conf crawler-conf.yaml -local"
</code></pre>

**Comment by jnioche** [comment]
I can't reproduce the issue at all. What OS and version of Maven are you on?

**Comment by jiangyt** [comment]
Apache Maven 3.0.5 (r01de14724cdef164cd33c7c8c2fe155faf9602da; 2013-02-19 21:51:28+0800)
Maven home: /usr/local/maven
Java version: 1.7.0_80, vendor: Oracle Corporation
Java home: /opt/software/jdk1.7.0_80/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "2.6.32-573.3.1.el6.x86_64", arch: "amd64", family: "unix"
OS: Red Hat Enterprise Linux Workstation release 6.7 (Santiago)

I have tried 0.6 & 0.7 both have the same issue

**Comment by jnioche** [comment]
Could you delete the Maven cache (e.g. ~/.m2/repository/) and try again?

On 7 November 2015 at 10:06, Yitao Jiang <notifications@github.com> wrote:

> Apache Maven 3.0.5 (r01de14724cdef164cd33c7c8c2fe155faf9602da; 2013-02-19
> 21:51:28+0800)
> Maven home: /usr/local/maven
> Java version: 1.7.0_80, vendor: Oracle Corporation
> Java home: /opt/software/jdk1.7.0_80/jre
> Default locale: en_US, platform encoding: UTF-8
> OS name: "linux", version: "2.6.32-573.3.1.el6.x86_64", arch: "amd64",
> family: "unix"
> OS: Red Hat Enterprise Linux Workstation release 6.7 (Santiago)
>
> I have tried 0.6 & 0.7 both have the same issue
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DigitalPebble/storm-crawler/issues/212#issuecomment-154688373>
> .
>



-- 



* Open Source Solutions for Text Engineering   http://www.digitalpebble.com
<http://www.digitalpebble.com>*
*http://digitalpebble.blogspot.com <http://digitalpebble.blogspot.com/>*
https://twitter.com/digitalpebble

**Comment by jiangyt** [comment]
yeah, it works. Thank you.
