### ISSUE TITLE
ES error when parsing never refetch date

### ISSUE THREAD

**Issue by sebastian-nagel** [DigitalPebble/storm-crawler#337]
Setting `fetchInterval.default: -1` to indicate that a page should never be refetched (see #331) causes an error in Elasticsearch:
```
[2016-09-21 13:51:45,354][DEBUG]... failed to execute bulk item (index) index {[status][status][...,"nextFetchDate":"292278994-08-17T07:12:55.807Z"}]}
MapperParsingException[failed to parse [nextFetchDate]]; nested: IllegalFieldValueException[Cannot parse "292278994-08-17T07:12:55.807Z": Value 292278994 for 
year must be in the range [-292275054,292278993]];
        at org.elasticsearch.index.mapper.FieldMapper.parse(FieldMapper.java:329)
...
Caused by: org.joda.time.IllegalFieldValueException: Cannot parse "292278994-08-17T07:12:55.807Z": Value 292278994 for year must be in the range [-292275054,2
92278993]
        at org.joda.time.field.FieldUtils.verifyValueBounds(FieldUtils.java:234)
        at org.joda.time.chrono.BasicYearDateTimeField.set(BasicYearDateTimeField.java:83)
        at org.joda.time.format.DateTimeParserBucket$SavedField.set(DateTimeParserBucket.java:568)
        at org.joda.time.format.DateTimeParserBucket.computeMillis(DateTimeParserBucket.java:447)
        at org.joda.time.format.DateTimeParserBucket.doParseMillis(DateTimeParserBucket.java:182)
        at org.joda.time.format.DateTimeFormatter.parseMillis(DateTimeFormatter.java:780)
        at org.elasticsearch.index.mapper.core.DateFieldMapper$DateFieldType.parseStringValue(DateFieldMapper.java:362)
```
The error is caused by an overflow with timezones and `new Date(Long.MAX_VALUE)`, see https://github.com/JodaOrg/joda-time/commit/d7774f13ad2dc7cf7295bb8376c21bbf5c662fc4.

**Comment by jnioche** [comment]
We could adopt another arbitrary value instead of Long.MAX_VALUE. I thought initially about using epoch but that required modifying all the spouts. Also using such a large value might have an impact on the storage in ES. Any suggestions? 100 years from now?

**Comment by sebastian-nagel** [comment]
I've tested successfully
```
public static final Date NEVER = new Date(
            Long.MAX_VALUE - 1000L * 60 * 60 * 24 * 365 * 2);
```
(two years before to be sure that the year does not overflow). Works, but a constant date far in the future is fine as well. Should be clear at a first glance that it means never, e.g. 2099-12-31 and it should be a constant to save storage space and make it easier to search for never-refetch items.
