### ISSUE TITLE
[ElasticSearch] "Result window is too large"

### ISSUE THREAD

**Issue by prokopidis** [DigitalPebble/storm-crawler#369]
Hi and thanks for SC. We have the following issue while running the elasticsearch module. Things work as expected in the beginning but after a while and with around 10800/80 discovered/fetched urls, the process dies with a "Result window is too large" message:

```
$ cd ~/src/storm-crawler/external/elasticsearch
$ cp ../../core/src/main/resources/crawler-default.yaml ./crawl-conf.yaml
$ mkdir -p src/main/resources
$ cp ../../archetype/src/main/resources/archetype-resources/src/main/resources/urlfilters.json src/main/resources/
$ grep hostURL -i -A4  src/main/resources/urlfilters.json 
      "class": "com.digitalpebble.stormcrawler.filtering.host.HostURLFilter",
      "name": "HostURLFilter",
      "params": {
        "ignoreOutsideHost": false,
        "ignoreOutsideDomain": true
      }
$ echo "https://en.wikipedia.org/wiki/Main_Page" > seeds.txt
$ ./ES_IndexInit.sh 
$ mvn clean install -P bigjar
$ storm jar target/storm-crawler-elasticsearch-*-SNAPSHOT.jar com.digitalpebble.stormcrawler.elasticsearch.ESSeedInjector . seeds.txt -local -conf es-conf.yaml -ttl 60
...
67995 [SessionTracker] INFO  o.a.s.s.o.a.z.s.SessionTrackerImpl - SessionTrackerImpl exited loop!
$ storm jar target/storm-crawler-elasticsearch-*-SNAPSHOT.jar com.digitalpebble.stormcrawler.elasticsearch.ESCrawlTopology -local -conf es-conf.yaml -conf crawl-conf.yaml
...
40816 [Thread-26-spout-executor[18 18]] INFO  c.d.s.e.p.ElasticSearchSpout - Populating buffer with nextFetchDate <= 2016-10-25T11:09:28.192+0300
40836 [Thread-26-spout-executor[18 18]] ERROR o.a.s.util - Async loop died!
org.elasticsearch.action.search.SearchPhaseExecutionException: all shards failed
        at org.elasticsearch.action.search.AbstractSearchAsyncAction.onFirstPhaseResult(AbstractSearchAsyncAction.java:206) ~[storm-crawler-elasticsearch-1.2-SNAPSHOT.jar:?]
        at org.elasticsearch.action.search.AbstractSearchAsyncAction$1.onFailure(AbstractSearchAsyncAction.java:152) ~[storm-crawler-elasticsearch-1.2-SNAPSHOT.jar:?]
        at org.elasticsearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:46) ~[storm-crawler-elasticsearch-1.2-SNAPSHOT.jar:?]
        at org.elasticsearch.transport.TransportService$DirectResponseChannel.processException(TransportService.java:872) ~[storm-crawler-elasticsearch-1.2-SNAPSHOT.jar:?]
        at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:850) ~[storm-crawler-elasticsearch-1.2-SNAPSHOT.jar:?]
        at org.elasticsearch.transport.TransportService$4.onFailure(TransportService.java:387) ~[storm-crawler-elasticsearch-1.2-SNAPSHOT.jar:?]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:39) ~[storm-crawler-elasticsearch-1.2-SNAPSHOT.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:1.8.0_91]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:1.8.0_91]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: org.elasticsearch.search.query.QueryPhaseExecutionException: Result window is too large, from + size must be less than or equal to: [10000] but was [10100]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level parameter.
        at org.elasticsearch.search.internal.DefaultSearchContext.preProcess(DefaultSearchContext.java:212) ~[storm-crawler-elasticsearch-1.2-SNAPSHOT.jar:?]
        at org.elasticsearch.search.query.QueryPhase.preProcess(QueryPhase.java:103) ~[storm-crawler-elasticsearch-1.2-SNAPSHOT.jar:?]
        at org.elasticsearch.search.SearchService.createContext(SearchService.java:689) ~[storm-crawler-elasticsearch-1.2-SNAPSHOT.jar:?]
        at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:633) ~[storm-crawler-elasticsearch-1.2-SNAPSHOT.jar:?]
        at org.elasticsearch.search.SearchService.executeDfsPhase(SearchService.java:264) ~[storm-crawler-elasticsearch-1.2-SNAPSHOT.jar:?]
        at org.elasticsearch.search.action.SearchServiceTransportAction$SearchDfsTransportHandler.messageReceived(SearchServiceTransportAction.java:360) ~[storm-crawler-elasticsearch-1.2-SNAPSHOT.jar:?]
        at org.elasticsearch.search.action.SearchServiceTransportAction$SearchDfsTransportHandler.messageReceived(SearchServiceTransportAction.java:357) ~[storm-crawler-elasticsearch-1.2-SNAPSHOT.jar:?]
        at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33) ~[storm-crawler-elasticsearch-1.2-SNAPSHOT.jar:?]
        at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:77) ~[storm-crawler-elasticsearch-1.2-SNAPSHOT.jar:?]
        at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:376) ~[storm-crawler-elasticsearch-1.2-SNAPSHOT.jar:?]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[storm-crawler-elasticsearch-1.2-SNAPSHOT.jar:?]
        ... 3 more
40850 [Thread-26-spout-executor[18 18]] ERROR o.a.s.d.executor - 
org.elasticsearch.action.search.SearchPhaseExecutionException: all shards failed
        at org.elasticsearch.action.search.AbstractSearchAsyncAction.onFirstPhaseResult(AbstractSearchAsyncAction.java:206) ~[storm-crawler-elasticsearch-1.2-SNAPSHOT.jar:?]
        at org.elasticsearch.action.search.AbstractSearchAsyncAction$1.onFailure(AbstractSearchAsyncAction.java:152) ~[storm-crawler-elasticsearch-1.2-SNAPSHOT.jar:?]
        at org.elasticsearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:46) ~[storm-crawler-elasticsearch-1.2-SNAPSHOT.jar:?]
        at org.elasticsearch.transport.TransportService$DirectResponseChannel.processException(TransportService.java:872) ~[storm-crawler-elasticsearch-1.2-SNAPSHOT.jar:?]
        at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:850) ~[storm-crawler-elasticsearch-1.2-SNAPSHOT.jar:?]
        at org.elasticsearch.transport.TransportService$4.onFailure(TransportService.java:387) ~[storm-crawler-elasticsearch-1.2-SNAPSHOT.jar:?]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:39) ~[storm-crawler-elasticsearch-1.2-SNAPSHOT.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[?:1.8.0_91]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[?:1.8.0_91]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: org.elasticsearch.search.query.QueryPhaseExecutionException: Result window is too large, from + size must be less than or equal to: [10000] but was [10100]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level parameter.
        at org.elasticsearch.search.internal.DefaultSearchContext.preProcess(DefaultSearchContext.java:212) ~[storm-crawler-elasticsearch-1.2-SNAPSHOT.jar:?]
        at org.elasticsearch.search.query.QueryPhase.preProcess(QueryPhase.java:103) ~[storm-crawler-elasticsearch-1.2-SNAPSHOT.jar:?]
        at org.elasticsearch.search.SearchService.createContext(SearchService.java:689) ~[storm-crawler-elasticsearch-1.2-SNAPSHOT.jar:?]
        at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:633) ~[storm-crawler-elasticsearch-1.2-SNAPSHOT.jar:?]
        at org.elasticsearch.search.SearchService.executeDfsPhase(SearchService.java:264) ~[storm-crawler-elasticsearch-1.2-SNAPSHOT.jar:?]
        at org.elasticsearch.search.action.SearchServiceTransportAction$SearchDfsTransportHandler.messageReceived(SearchServiceTransportAction.java:360) ~[storm-crawler-elasticsearch-1.2-SNAPSHOT.jar:?]
        at org.elasticsearch.search.action.SearchServiceTransportAction$SearchDfsTransportHandler.messageReceived(SearchServiceTransportAction.java:357) ~[storm-crawler-elasticsearch-1.2-SNAPSHOT.jar:?]
        at org.elasticsearch.transport.TransportRequestHandler.messageReceived(TransportRequestHandler.java:33) ~[storm-crawler-elasticsearch-1.2-SNAPSHOT.jar:?]
        at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:77) ~[storm-crawler-elasticsearch-1.2-SNAPSHOT.jar:?]
        at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:376) ~[storm-crawler-elasticsearch-1.2-SNAPSHOT.jar:?]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[storm-crawler-elasticsearch-1.2-SNAPSHOT.jar:?]
        ... 3 more
40852 [Thread-30-fetch-executor[9 9]] WARN  c.d.s.p.h.HttpProtocol - HTTP content trimmed to 65536
40852 [Thread-30-fetch-executor[9 9]] INFO  c.d.s.b.SimpleFetcherBolt - [Fetcher #9] Fetched https://cy.wikiquote.org/wiki/Hafan with status 200 in 125 after waiting 0
40860 [Thread-50-parse-executor[15 15]] INFO  c.d.s.b.JSoupParserBolt - Parsing : starting https://cy.wikiquote.org/wiki/Hafan
40864 [Thread-14-fetch-executor[8 8]] INFO  c.d.s.b.SimpleFetcherBolt - [Fetcher #8] Fetched https://be-x-old.wikipedia.org/wiki/%D0%93%D0%B0%D0%BB%D0%BE%D1%9E%D0%BD%D0%B0%D1%8F_%D1%81%D1%82%D0%B0%D1%80%D0%BE%D0%BD%D0%BA%D0%B0 with status 301 in 62 after waiting 0
40871 [Thread-50-parse-executor[15 15]] INFO  c.d.s.b.JSoupParserBolt - Parsed https://cy.wikiquote.org/wiki/Hafan in 9 msec
40935 [Thread-48-fetch-executor[4 4]] INFO  c.d.s.b.SimpleFetcherBolt - [Fetcher #4] Fetched https://lists.wikimedia.org/mailman/listinfo/wikipedia-l with status 200 in 246 after waiting 999
40939 [Thread-50-parse-executor[15 15]] INFO  c.d.s.b.JSoupParserBolt - Parsing : starting https://lists.wikimedia.org/mailman/listinfo/wikipedia-l
40944 [Thread-50-parse-executor[15 15]] INFO  c.d.s.b.JSoupParserBolt - Parsed https://lists.wikimedia.org/mailman/listinfo/wikipedia-l in 3 msec
41075 [Thread-26-spout-executor[18 18]] ERROR o.a.s.util - Halting process: ("Worker died")
java.lang.RuntimeException: ("Worker died")
        at org.apache.storm.util$exit_process_BANG_.doInvoke(util.clj:341) [storm-core-1.0.2.jar:1.0.2]
        at clojure.lang.RestFn.invoke(RestFn.java:423) [clojure-1.7.0.jar:?]
        at org.apache.storm.daemon.worker$fn__8659$fn__8660.invoke(worker.clj:761) [storm-core-1.0.2.jar:1.0.2]
        at org.apache.storm.daemon.executor$mk_executor_data$fn__7875$fn__7876.invoke(executor.clj:274) [storm-core-1.0.2.jar:1.0.2]
        at org.apache.storm.util$async_loop$fn__624.invoke(util.clj:494) [storm-core-1.0.2.jar:1.0.2]
        at clojure.lang.AFn.run(AFn.java:22) [clojure-1.7.0.jar:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
```

**Comment by jnioche** [comment]
Thanks @prokopidis for reporting this. You could use the AggregationSpout as an alternative but I'll have a look at this in the meantime.

**Comment by jnioche** [comment]
The param 'es.status.max.secs.date' should be set to prevent deep paging, see [https://github.com/DigitalPebble/storm-crawler/blob/master/external/elasticsearch/src/main/java/com/digitalpebble/stormcrawler/elasticsearch/persistence/ElasticSearchSpout.java#L59]. It is inactive by default but it would be a good idea to set it in es-conf.yaml so that users are more aware of it.

**Comment by jnioche** [comment]
@prokopidis could you please give the change I just committed a try? Thanks!

**Comment by prokopidis** [comment]
The `es.status.max.secs.date: 100` is read from the conf when the spout is opened, but the same error occurs.

**Comment by jnioche** [comment]
Ok, you've tried a lower value I presume (e.g. 30)?

**Comment by jnioche** [comment]
Ok, there are several issues here. The main one is that ElasticSearchSpout does not throttle the calls to ES, like the AggregationSpout(s) do. In your case it means that we quickly send far too many requests without  es.status.max.secs.date having time to kick in. I'll move the throttling from AggregationSpout to the abstract class and force ESS to use it.

The trouble in your case is that you are copying the default config values from '../../core/src/main/resources/crawler-default.yaml' - these are loaded from the jars anyway and are missing some configs that can be found in [https://github.com/DigitalPebble/storm-crawler/blob/master/archetype/src/main/resources/archetype-resources/crawler-conf.yaml] like max spout pending. The latter sets a limit to the # of URLs in process and blocks the spout. Since you are not specifying it, the spout reads constantly from ES and pushes the URLs to the topology. This is a recipe for disaster, especially since your crawl uses a single domain, the URLs will get stuck in the internal queues and in the best case time out or lead to a memory exception.

Either use the archetype and add the ES bits that are missing or build by hand but in that case don't use the default conf file. Makes sense?

**Comment by prokopidis** [comment]
Thank you @jnioche for the explanation and the solutions. Perhaps it would be helpful if the link to the archetypes conf was mentioned as a starting point in the ES module documentation.

**Comment by jnioche** [comment]
You are welcome @prokopidis. See #370 for a PR which adds ad delay between calls to ES in the ESSpout.

> Perhaps it would be helpful if the link to the archetypes conf was mentioned as a starting point in the ES module documentation

Could do or we could add some instructions on how to modify the files generated by a call to the archetype

**Comment by jnioche** [comment]
@prokopidis see #372 for resources and instructions on using the archetype with ES
