### ISSUE TITLE
Error when running storm in local mode without storm installed 

### ISSUE THREAD

**Issue by normansuesstrunk** [DigitalPebble/storm-crawler#403]
After a fresh bootstrap of a stormcrawler project with the mvn archetype command, i tried to run the example with 

```sh
mvn clean compile exec:java -Dexec.mainClass=[package].CrawlTopology -Dexec.args="-conf crawler-conf.yaml -local"

The app gets started and crashes with the following error: 

``` 
194391 [Thread-7-EventThread] INFO  o.a.s.s.o.a.z.ClientCnxn - EventThread shut down
194401 [Thread-7] INFO  o.a.s.d.supervisor - Copying resources at jar:file:/home/suesstnorma1/.m2/repository/org/apache/storm/flux-core/1.0.2/flux-core-1.0.2.jar!/resources to /tmp/bb8f0408-35d1-4451-b03d-ecd4b18dd7d2/supervisor/stormdist/crawl-1-1483700678/resources
194401 [Thread-7] ERROR o.a.s.event - Error when processing event
java.io.FileNotFoundException: Source 'file:/home/suesstnorma1/.m2/repository/org/apache/storm/flux-core/1.0.2/flux-core-1.0.2.jar!/resources' does not exist
	at org.apache.storm.shade.org.apache.commons.io.FileUtils.checkFileRequirements(FileUtils.java:1405) ~[storm-core-1.0.2.jar:1.0.2]
	at org.apache.storm.shade.org.apache.commons.io.FileUtils.copyDirectory(FileUtils.java:1368) ~[storm-core-1.0.2.jar:1.0.2]
	at org.apache.storm.shade.org.apache.commons.io.FileUtils.copyDirectory(FileUtils.java:1268) ~[storm-core-1.0.2.jar:1.0.2]
	at org.apache.storm.shade.org.apache.commons.io.FileUtils.copyDirectory(FileUtils.java:1237) ~[storm-core-1.0.2.jar:1.0.2]
	at org.apache.storm.daemon.supervisor$fn__9436.invoke(supervisor.clj:1178) ~[storm-core-1.0.2.jar:1.0.2]
	at clojure.lang.MultiFn.invoke(MultiFn.java:243) ~[clojure-1.7.0.jar:?]
	at org.apache.storm.daemon.supervisor$mk_synchronize_supervisor$this__9163$fn__9181.invoke(supervisor.clj:579) ~[storm-core-1.0.2.jar:1.0.2]
	at org.apache.storm.daemon.supervisor$mk_synchronize_supervisor$this__9163.invoke(supervisor.clj:578) ~[storm-core-1.0.2.jar:1.0.2]
	at org.apache.storm.event$event_manager$fn__8735.invoke(event.clj:40) [storm-core-1.0.2.jar:1.0.2]
	at clojure.lang.AFn.run(AFn.java:22) [clojure-1.7.0.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
194408 [Thread-7] ERROR o.a.s.util - Halting process: ("Error when processing an event")
java.lang.RuntimeException: ("Error when processing an event")
	at org.apache.storm.util$exit_process_BANG_.doInvoke(util.clj:341) [storm-core-1.0.2.jar:1.0.2]
	at clojure.lang.RestFn.invoke(RestFn.java:423) [clojure-1.7.0.jar:?]
	at org.apache.storm.event$event_manager$fn__8735.invoke(event.clj:48) [storm-core-1.0.2.jar:1.0.2]
	at clojure.lang.AFn.run(AFn.java:22) [clojure-1.7.0.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
```

I cleaned my local maven repo and re-executed, but it did not help. 

Many thanks

**Comment by jnioche** [comment]
Hi @normansuesstrunk 

This is a known issue, see #324

I will remove the instructions from the README generated by the archetype. You will need to install Storm to run StormCrawler.

Thanks!

**Comment by normansuesstrunk** [comment]
many thanks. i searched the issue but i missed that one. sorry for that.

**Comment by jnioche** [comment]
no problem, this is a useful reminder for me to fix the README file! thanks!
