### ISSUE TITLE
not serializable exception caused by kryo.writeobject()

### ISSUE THREAD

**Issue by rch49** [DigitalPebble/storm-crawler#416]
Hi!
I'm writing a storm topology in which the object transmitted between bolds are opencv:Mat. The problem is that these object are not serializable and opencv:MAt are not tansmitted. I've write a custom serialization using kryo. But I'm still getting not serializable exception caused by kryo.writeobject().
Any suggestion Please!

**Comment by rch49** [comment]
this is the exception I'm getting:
java.lang.RuntimeException: java.lang.RuntimeException: java.io.NotSerializableException: org.opencv.core.Mat
        at backtype.storm.utils.DisruptorQueue.consumeBatchToCursor(DisruptorQueue.java:135) ~[storm-core-0.9.6.jar:0.9.6]
        at backtype.storm.utils.DisruptorQueue.consumeBatchWhenAvailable(DisruptorQueue.java:106) ~[storm-core-0.9.6.jar:0.9.6]
        at backtype.storm.disruptor$consume_batch_when_available.invoke(disruptor.clj:80) ~[storm-core-0.9.6.jar:0.9.6]
        at backtype.storm.disruptor$consume_loop_STAR_$fn__1458.invoke(disruptor.clj:94) ~[storm-core-0.9.6.jar:0.9.6]
        at backtype.storm.util$async_loop$fn__460.invoke(util.clj:463) ~[storm-core-0.9.6.jar:0.9.6]
        at clojure.lang.AFn.run(AFn.java:24) [clojure-1.5.1.jar:na]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111]
Caused by: java.lang.RuntimeException: java.io.NotSerializableException: org.opencv.core.Mat
        at backtype.storm.serialization.SerializableSerializer.write(SerializableSerializer.java:41) ~[storm-core-0.9.6.jar:0.9.6]
        at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:501) ~[kryo-2.21.jar:na]
        at com.mycompany.app.DataBeankryo.write(DataBeankryo.java:24) ~[stormjar.jar:na]
        at com.mycompany.app.DataBeankryo.write(DataBeankryo.java:10) ~[stormjar.jar:na]
        at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:568) ~[kryo-2.21.jar:na]
        at com.esotericsoftware.kryo.serializers.CollectionSerializer.write(CollectionSerializer.java:75) ~[kryo-2.21.jar:na]
        at com.esotericsoftware.kryo.serializers.CollectionSerializer.write(CollectionSerializer.java:18) ~[kryo-2.21.jar:na]
        at com.esotericsoftware.kryo.Kryo.writeObject(Kryo.java:486) ~[kryo-2.21.jar:na]
        at backtype.storm.serialization.KryoValuesSerializer.serializeInto(KryoValuesSerializer.java:44) ~[storm-core-0.9.6.jar:0.9.6]
        at backtype.storm.serialization.KryoTupleSerializer.serialize(KryoTupleSerializer.java:44) ~[storm-core-0.9.6.jar:0.9.6]
        at backtype.storm.daemon.worker$mk_transfer_fn$fn__4425.invoke(worker.clj:130) ~[storm-core-0.9.6.jar:0.9.6]
        at backtype.storm.daemon.executor$start_batch_transfer__GT_worker_handler_BANG_$fn__3281.invoke(executor.clj:259) ~[storm-core-0.9.6.j$
        at backtype.storm.disruptor$clojure_handler$reify__1445.onEvent(disruptor.clj:58) ~[storm-core-0.9.6.jar:0.9.6]
        at backtype.storm.utils.DisruptorQueue.consumeBatchToCursor(DisruptorQueue.java:132) ~[storm-core-0.9.6.jar:0.9.6]
        ... 6 common frames omitted

**Comment by jnioche** [comment]
This is unrelated to StormCrawler.
