### ISSUE TITLE
Receiving org.apache.storm.utils.NimbusLeaderNotFoundException as executed CrawlTopology

### ISSUE THREAD

**Issue by isspek** [DigitalPebble/storm-crawler#417]
I created  new StormCrawler-based project by following steps described in [I](https://github.com/DigitalPebble/storm-crawler). Without modifying crawler-confer.yaml, I executed CrawlTopology.java which comes with the project and then I received error as below:

```
org.apache.storm.utils.NimbusLeaderNotFoundException: Could not find leader nimbus from seed hosts [localhost]. Did you specify a valid list of nimbus hosts for config nimbus.seeds?
	at org.apache.storm.utils.NimbusClient.getConfiguredClientAs(NimbusClient.java:90)
	at org.apache.storm.StormSubmitter.topologyNameExists(StormSubmitter.java:371)
	at org.apache.storm.StormSubmitter.submitTopologyAs(StormSubmitter.java:233)
	at org.apache.storm.StormSubmitter.submitTopology(StormSubmitter.java:311)
	at org.apache.storm.StormSubmitter.submitTopology(StormSubmitter.java:157)
	at com.digitalpebble.stormcrawler.ConfigurableTopology.submit(ConfigurableTopology.java:85)
        at com.mycompany.crawler.CrawlTopology.run(CrawlTopology.java:68)
	at com.digitalpebble.stormcrawler.ConfigurableTopology.start(ConfigurableTopology.java:50)
	at com.mycompany.crawler.CrawlTopology.main(CrawlTopology.java:38)
```
I searched Google what the problem causes, it seems related Zookeper. But I am using Tomcat server. What should I do for preventing this error?

**Comment by sebastian-nagel** [comment]
How was the CrawlTopology executed? Normally, the execution is done by Storm:
```
storm jar .../path/to/storm-crawler.jar com.digitalpebble.stormcrawler.CrawlTopology -conf ...
```

**Comment by isspek** [comment]
@sebastian-nagel I created it as Maven Project in Eclipse. I wanted to figure out how crawler works. So I executed main method by running as application in Eclipse and then I got these errors. I haven't installed Storm on my machine, because it is already in pom. Should I install it on my machine?

**Comment by jnioche** [comment]
Add `-local and conf crawler-conf.yaml` as argument to the topology class. You don't have to run it with Storm, it works with Eclipse. If local is not specified, it tries to connect to a Storm cluster and since you haven't installed one you are getting this error

**Comment by sebastian-nagel** [comment]
The wiki contains a description how to [run the topology locally](https://github.com/DigitalPebble/storm-crawler/wiki/Configuration).

**Comment by jnioche** [comment]
@sebastian-nagel that wiki page needs fixing. Running with mvn-exec does not work, see #324 

The README file generated by the archetype contains the correct instructions i.e run it with Storm installed (but it also works with Eclipse and is a good way of debugging)
