### ISSUE TITLE
Running under apache storm v 2.10

### ISSUE THREAD

**Issue by ravi-b-m** [DigitalPebble/storm-crawler#795]
I have installed the latest version of storm 2.1.0 and trying to run my topology under local mode in the local storm cluster.. I get the following exception
```
17:14:21.987 [main] INFO  o.a.s.m.StormMetricsRegistry - Started statistics report plugin...
Exception in thread "main" java.lang.NoSuchMethodError: org.apache.storm.LocalCluster.submitTopology(Ljava/lang/String;Ljava/util/Map;Lorg/apache/storm/generated/StormTopology;)V
	at com.digitalpebble.stormcrawler.ConfigurableTopology.submit(ConfigurableTopology.java:76)
	at abbvie.ir.pikm.CrawlTopology.run(CrawlTopology.java:119)
	at com.digitalpebble.stormcrawler.ConfigurableTopology.start(ConfigurableTopology.java:50)
	at abbvie.ir.pikm.CrawlTopology.main(CrawlTopology.java:46)
```

Is the latest version of storm supported ??

**Comment by sebastian-nagel** [comment]
There is a branch to run storm-crawler on [Storm 2.x](https://github.com/DigitalPebble/storm-crawler/tree/2.x). However, be aware of [STORM-3582](https://issues.apache.org/jira/projects/STORM/issues/STORM-3582).
