### ISSUE TITLE
HttpHeaders#formatDate fails to parse date and returns always an empty string

### ISSUE THREAD

**Issue by sebastian-nagel** [DigitalPebble/storm-crawler#821]
The method [HttpHeaders#formatDate](https://github.com/DigitalPebble/storm-crawler/blob/54bb5934918ff0f8919d58372405cfb14d63ad93/core/src/main/java/com/digitalpebble/stormcrawler/protocol/HttpHeaders.java#L86) fails to parse the ISO date holding the last-modified time with the exception
```
java.time.format.DateTimeParseException: Text '2020-09-22T08:00:00.000Z' could not be parsed: Unable to obtain ZonedDateTime from TemporalAccesso
r: {InstantSeconds=1600761600, NanoOfSecond=0, MicroOfSecond=0, MilliOfSecond=0},ISO of type java.time.format.Parsed
        at java.time.format.DateTimeFormatter.createError(DateTimeFormatter.java:1920)
        at java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1855)
        at com.digitalpebble.stormcrawler.protocol.HttpHeaders.formatHttpDate(HttpHeaders.java:88)
        ...
```
which is caught and an empty string is returned. As a consequence the HTTP protocols will send the "If-modified-since" HTTP header with an empty date. So, Last-modified handling is broken due to this bug. See also: #673 and #674 which introduced this bug. A unit test to verify #820 uncovered it.

The exception is caused because the [ISO_INSTANT DateTimeFormatter](https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html#ISO_INSTANT) requires that a timezone (UTC) is provided.

**Comment by sebastian-nagel** [comment]
Verified that the "If-modified-since" header is **not** properly sent using the main method of HTTP protocols and the option `http.store.headers: true`:
```
java -cp ... com.digitalpebble.stormcrawler.protocol.okhttp.HttpProtocol -c ./conf/crawler-conf-test.yaml $'http://localhost/\tlast-modified=2019-11-01T20:00:00.000Z'
_request.headers_: GET / HTTP/1.1
User-Agent: ...
Accept: ...
Accept-Language: ...
If-Modified-Since: 
...

status code: 200
...
```
