### ISSUE TITLE
Exception in thread "main" java.lang.ClassNotFoundException: org.apache.storm.flux.Flux

### ISSUE THREAD

**Issue by guspatrick** [DigitalPebble/storm-crawler#844]
Running Storm Crawler Elasticsearch Archetype version 2.0, with JDK 11 and Apache Storm 2.1, yields the following error:

Exception in thread "main" java.lang.ClassNotFoundException: org.apache.storm.flux.Flux
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:315)
	at org.apache.storm.LocalCluster.lambda$main$1(LocalCluster.java:395)
	at org.apache.storm.LocalCluster.withLocalModeOverride(LocalCluster.java:347)
	at org.apache.storm.LocalCluster.main(LocalCluster.java:392)

**Comment by guspatrick** [comment]
Solved: I ran mvn package clean instead of mvn clean package. There was no target folder.
