### ISSUE TITLE
getCharsetFromMeta StringIndexOutOfBoundsException: String index out of range: -9999

### ISSUE THREAD

**Issue by jnioche** [DigitalPebble/storm-crawler#870]
19633413 [Thread-24-parse-executor[7 7]] INFO  c.d.s.b.JSoupParserBolt - Parsing : starting https://indicator.natwest.com:443/
19633417 [Thread-24-parse-executor[7 7]] ERROR o.a.s.util - Async loop died!
java.lang.RuntimeException: java.lang.StringIndexOutOfBoundsException: String index out of range: -9999
	at org.apache.storm.utils.DisruptorQueue.consumeBatchToCursor(DisruptorQueue.java:522) ~[storm-core-1.2.3.jar:1.2.3]
	at org.apache.storm.utils.DisruptorQueue.consumeBatchWhenAvailable(DisruptorQueue.java:487) ~[storm-core-1.2.3.jar:1.2.3]
	at org.apache.storm.disruptor$consume_batch_when_available.invoke(disruptor.clj:74) ~[storm-core-1.2.3.jar:1.2.3]
	at org.apache.storm.daemon.executor$fn__10180$fn__10193$fn__10246.invoke(executor.clj:861) ~[storm-core-1.2.3.jar:1.2.3]
	at org.apache.storm.util$async_loop$fn__624.invoke(util.clj:484) [storm-core-1.2.3.jar:1.2.3]
	at clojure.lang.AFn.run(AFn.java:22) [clojure-1.7.0.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -9999
	at java.lang.String.substring(String.java:1967) ~[?:1.8.0_282]
	at com.digitalpebble.stormcrawler.util.CharsetIdentification.getCharsetFromMeta(CharsetIdentification.java:189) ~[crawlurlfrontier-1.0-SNAPSHOT.jar:?]
	at com.digitalpebble.stormcrawler.util.CharsetIdentification.getCharsetFast(CharsetIdentification.java:56) ~[crawlurlfrontier-1.0-SNAPSHOT.jar:?]
	at com.digitalpebble.stormcrawler.bolt.JSoupParserBolt.execute(JSoupParserBolt.java:227) ~[crawlurlfrontier-1.0-SNAPSHOT.jar:?]
	at org.apache.storm.daemon.executor$fn__10180$tuple_action_fn__10182.invoke(executor.clj:739) ~[storm-core-1.2.3.jar:1.2.3]
	at org.apache.storm.daemon.executor$mk_task_receiver$fn__10101.invoke(executor.clj:468) ~[storm-core-1.2.3.jar:1.2.3]
	at org.apache.storm.disruptor$clojure_handler$reify__9612.onEvent(disruptor.clj:41) ~[storm-core-1.2.3.jar:1.2.3]
	at org.apache.storm.utils.DisruptorQueue.consumeBatchToCursor(DisruptorQueue.java:509) ~[storm-core-1.2.3.jar:1.2.3]
	... 6 more

**Comment by kkrugler** [comment]
If the subsequent `"` isn't found (so `end == -1`), then `substring()` shouldn't be called here:

``` java
        // fast search for e.g. <meta charset="utf-8">
        // might not get it 100% but should be frequent enough
        // and faster than parsing
        int start = html.indexOf("<meta charset=\"");
        if (start != -1) {
            int end = html.indexOf('"', start + 15);
            return validateCharset(html.substring(start + 15, end));
        }
```

But I don't see how either index to `substring()` could be -9999.

**Comment by jnioche** [comment]
@kkrugler, you are right. 

we take up to 10K characters to find the charset and on that particular URL, the charset info is at the very end but is cut before it finishes

    _<meta charset="u_
    
The exception message thrown by _substring()_ is confusing indeed.

Will fix shortly
